/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSuccessRouteImport } from './routes/_site.success'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SiteIntakeRouteImport } from './routes/_site.intake'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteBookRouteImport } from './routes/_site.book'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSuccessRoute = SiteSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntakeRoute = SiteIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBookRoute = SiteBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/book': typeof SiteBookRoute
  '/contact': typeof SiteContactRoute
  '/intake': typeof SiteIntakeRoute
  '/pricing': typeof SitePricingRoute
  '/services': typeof SiteServicesRoute
  '/success': typeof SiteSuccessRoute
}
export interface FileRoutesByTo {
  '/book': typeof SiteBookRoute
  '/contact': typeof SiteContactRoute
  '/intake': typeof SiteIntakeRoute
  '/pricing': typeof SitePricingRoute
  '/services': typeof SiteServicesRoute
  '/success': typeof SiteSuccessRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/book': typeof SiteBookRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/intake': typeof SiteIntakeRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/success': typeof SiteSuccessRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/contact'
    | '/intake'
    | '/pricing'
    | '/services'
    | '/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/book'
    | '/contact'
    | '/intake'
    | '/pricing'
    | '/services'
    | '/success'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/book'
    | '/_site/contact'
    | '/_site/intake'
    | '/_site/pricing'
    | '/_site/services'
    | '/_site/success'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/success': {
      id: '/_site/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SiteSuccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/intake': {
      id: '/_site/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof SiteIntakeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/book': {
      id: '/_site/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof SiteBookRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteBookRoute: typeof SiteBookRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteIntakeRoute: typeof SiteIntakeRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteSuccessRoute: typeof SiteSuccessRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteBookRoute: SiteBookRoute,
  SiteContactRoute: SiteContactRoute,
  SiteIntakeRoute: SiteIntakeRoute,
  SitePricingRoute: SitePricingRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteSuccessRoute: SiteSuccessRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
